version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: catalert_db
      POSTGRES_USER: catalert_user
      POSTGRES_PASSWORD: catalert_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalert_user -d catalert_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CatAlert Backend API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://catalert_user:catalert_password@postgres:5432/catalert_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker (for background tasks)
  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://catalert_user:catalert_password@postgres:5432/catalert_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: celery -A app.core.celery worker --loglevel=info

  # Celery Beat (for scheduled tasks)
  beat:
    build: .
    environment:
      - DATABASE_URL=postgresql://catalert_user:catalert_password@postgres:5432/catalert_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: celery -A app.core.celery beat --loglevel=info

  # Flower (Celery monitoring)
  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://catalert_user:catalert_password@postgres:5432/catalert_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
    command: celery -A app.core.celery flower --port=5555

volumes:
  postgres_data:
  redis_data:
